language: ruby
cache: bundler

rvm:
  - 2.2.2

before_install:
  - 'npm install'

services:
  - redis-server

before_script:
  - npm install -g bower
  - bower install

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - sebastian.schkudlara@vizzuality.com
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: c5c128fcb301371d4b89bec2df714028e0a75deb8d732f49f922626aa84c3524